# Generated by Django 4.0.3 on 2022-03-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('identitycard', models.IntegerField()),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('glucouse', models.FloatField()),
                ('insuline', models.FloatField()),
                ('homa', models.FloatField()),
                ('leptin', models.FloatField()),
                ('adiponcetin', models.FloatField()),
                ('resistiin', models.FloatField()),
                ('mcp', models.FloatField()),
                ('classification', models.CharField(max_length=10)),
            ],
        ),
    ]
